### ISSUE TITLE
error http://bower.io/search/

### ISSUE THREAD

**Issue by kuldipem** [bower/search#72] opened 2015-05-01 09:57 UTC
I found following error in http://bower.io/search/  on console.

<code>Error: group[0].website is undefined
[7]</module.exports/</dedupe/<@http://bower.io/search/dist/app.js:9:9383
runInContext/forOwn@http://bower.io/search/dist/app.js:8:27488
forEach@http://bower.io/search/dist/app.js:8:2279
[7]</module.exports/</dedupe@http://bower.io/search/dist/app.js:9:9303
[7]</module.exports/</$scope.search@http://bower.io/search/dist/app.js:9:10173
[7]</module.exports/<@http://bower.io/search/dist/app.js:9:11044
invoke@http://bower.io/search/dist/app.js:2:3621
instantiate@http://bower.io/search/dist/app.js:2:3846
$ControllerProvider/this.$get</<@http://bower.io/search/dist/app.js:3:8463
nodeLinkFn/<@http://bower.io/search/dist/app.js:2:24052
forEach@http://bower.io/search/dist/app.js:1:9010
nodeLinkFn@http://bower.io/search/dist/app.js:2:23723
compositeLinkFn@http://bower.io/search/dist/app.js:2:15668
compile/<@http://bower.io/search/dist/app.js:2:14586
bootstrap/doBootstrap/</<@http://bower.io/search/dist/app.js:1:18313
$RootScopeProvider/this.$get</Scope.prototype.$eval@http://bower.io/search/dist/app.js:4:18826
$RootScopeProvider/this.$get</Scope.prototype.$apply@http://bower.io/search/dist/app.js:4:19179
bootstrap/doBootstrap/<@http://bower.io/search/dist/app.js:1:18254
invoke@http://bower.io/search/dist/app.js:2:3621
bootstrap/doBootstrap@http://bower.io/search/dist/app.js:1:18134
bootstrap@http://bower.io/search/dist/app.js:1:18447
angularInit@http://bower.io/search/dist/app.js:1:17625
[2]</</<@http://bower.io/search/dist/app.js:7:12605
trigger@http://bower.io/search/dist/app.js:5:20003
createEventHandler/eventHandler/<@http://bower.io/search/dist/app.js:1:31507
forEach@http://bower.io/search/dist/app.js:1:8856
createEventHandler/eventHandler@http://bower.io/search/dist/app.js:1:31468

http://bower.io/search/dist/app.js
Line 3</code>

**Comment by desandro** [comment] 2015-05-03 12:47
Do you remember what you searched for to get this error?

**Comment by kuldipem** [comment] 2015-05-04 04:25
I searched "highlight.js" .

**Comment by anhskohbo** [comment] 2015-05-20 14:50
Some problem in Firefox, Chrome work fine.

![screenshot from 2015-05-20 21-49-11](https://cloud.githubusercontent.com/assets/1529454/7728564/2e30c778-ff3a-11e4-8649-4189c3815fdc.png)

**Comment by rbecheras** [comment] 2015-06-02 15:33
+1

**Comment by samccone** [comment] 2015-06-02 15:58
@rbecheras mind giving step to reproduce please?

**Comment by rbecheras** [comment] 2015-06-02 16:22
Just go to http://bower.io/search and the error occurs:

	"Error: group[0].website is undefined
	[7]</module.exports/</dedupe/<@http://bower.io/search/dist/app.js:9:9383
	runInContext/forOwn@http://bower.io/search/dist/app.js:8:27488
	forEach@http://bower.io/search/dist/app.js:8:2279
	[7]</module.exports/</dedupe@http://bower.io/search/dist/app.js:9:9303
	[7]</module.exports/</$scope.search@http://bower.io/search/dist/app.js:9:10173
	[7]</module.exports/<@http://bower.io/search/dist/app.js:9:11044
	invoke@http://bower.io/search/dist/app.js:2:3621
	instantiate@http://bower.io/search/dist/app.js:2:3846
	$ControllerProvider/this.$get</<@http://bower.io/search/dist/app.js:3:8463
	nodeLinkFn/<@http://bower.io/search/dist/app.js:2:24052
	forEach@http://bower.io/search/dist/app.js:1:9010
	nodeLinkFn@http://bower.io/search/dist/app.js:2:23723
	compositeLinkFn@http://bower.io/search/dist/app.js:2:15668
	compile/<@http://bower.io/search/dist/app.js:2:14586
	bootstrap/doBootstrap/</<@http://bower.io/search/dist/app.js:1:18313
	$RootScopeProvider/this.$get</Scope.prototype.$eval@http://bower.io/search/dist/app.js:4:18826
	$RootScopeProvider/this.$get</Scope.prototype.$apply@http://bower.io/search/dist/app.js:4:19179
	bootstrap/doBootstrap/<@http://bower.io/search/dist/app.js:1:18254
	invoke@http://bower.io/search/dist/app.js:2:3621
	bootstrap/doBootstrap@http://bower.io/search/dist/app.js:1:18134
	bootstrap@http://bower.io/search/dist/app.js:1:18447
	angularInit@http://bower.io/search/dist/app.js:1:17625
	[2]</</<@http://bower.io/search/dist/app.js:7:12605
	trigger@http://bower.io/search/dist/app.js:5:20003
	createEventHandler/eventHandler/<@http://bower.io/search/dist/app.js:1:31507
	forEach@http://bower.io/search/dist/app.js:1:8856
	createEventHandler/eventHandler@http://bower.io/search/dist/app.js:1:31468
	"

I am on Ubuntu 14.04 with Firefox 38.0 

    firefox 38.0+build3-0ubuntu0.14.04.1

I confirm with chrome there is no error 

    chromium-browser 41.0.2272.76-0ubuntu0.14.04.1.1076

And I've can see that on windows 7 with firefox 38.0, there is no error.

Weird bug...
And it is there from several days/weeks

**Comment by rbecheras** [comment] 2015-06-02 16:26
![bower-search-firefox-bug](https://cloud.githubusercontent.com/assets/6469390/7941032/d8c9e9a2-0954-11e5-9c60-30d21ee6ced6.png)

**Comment by agershun** [comment] 2015-06-08 06:24
@desandro Could you also check this issue: unfortunately, the search can not find ```alasql``` package
```
http://bower.io/search/?q=alasql
```
while the standard command-like search it is ok:
```
>bower search alasql
Search results:

    alasql git://github.com/agershun/alasql.git
```

Thank you!

**Comment by franciscop** [comment] 2015-07-22 08:54
+1, exactly the same as @rbecheras but in Firefox 39.0 and in Ubuntu 15.04

**Comment by BenMann** [comment] 2015-12-10 07:48
Same as #78. Closing.

**Closed by BenMann** 2015-12-10 07:48 UTC
